// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using gestionhotel.Models;

#nullable disable

namespace gestionhotel.Migrations.Hotel
{
    [DbContext(typeof(HotelContext))]
    [Migration("20250125182156_Addclient_idToReservation")]
    partial class Addclient_idToReservation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("gestionhotel.Models.Chambre", b =>
                {
                    b.Property<int>("ChambreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("chambre_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChambreId"));

                    b.Property<int?>("Capacite")
                        .HasColumnType("int")
                        .HasColumnName("capacite");

                    b.Property<string>("DescriptionChambre")
                        .HasColumnType("text")
                        .HasColumnName("description_chambre");

                    b.Property<string>("StatutChambre")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("statut_chambre");

                    b.Property<double?>("TarifParNuit")
                        .HasColumnType("float")
                        .HasColumnName("tarif_par_nuit");

                    b.Property<string>("TypeChambre")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("type_chambre");

                    b.HasKey("ChambreId")
                        .HasName("PK__chambre__645F7B5E5708DAC0");

                    b.ToTable("chambre", (string)null);
                });

            modelBuilder.Entity("gestionhotel.Models.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("client_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientId"));

                    b.Property<string>("Adresse")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("adresse");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<int?>("FideliteId")
                        .HasColumnType("int")
                        .HasColumnName("fidelite_id");

                    b.Property<string>("Historique")
                        .HasColumnType("text")
                        .HasColumnName("historique");

                    b.Property<string>("Nom")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nom");

                    b.Property<string>("NumeroTelephone")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("numero_telephone");

                    b.Property<string>("Preference")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("preference");

                    b.Property<string>("Prenom")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("prenom");

                    b.HasKey("ClientId")
                        .HasName("PK__client__BF21A424FE661190");

                    b.HasIndex("FideliteId");

                    b.ToTable("client", (string)null);
                });

            modelBuilder.Entity("gestionhotel.Models.Fidelite", b =>
                {
                    b.Property<int>("FideliteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("fidelite_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FideliteId"));

                    b.Property<string>("NiveauFidelite")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("niveau_fidelite");

                    b.Property<string>("OffreFidelite")
                        .HasColumnType("text")
                        .HasColumnName("offre_fidelite");

                    b.Property<int?>("PointsFidelite")
                        .HasColumnType("int")
                        .HasColumnName("points_fidelite");

                    b.HasKey("FideliteId")
                        .HasName("PK__fidelite__ACA6C5FEDE1E3CF0");

                    b.ToTable("fidelite", (string)null);
                });

            modelBuilder.Entity("gestionhotel.Models.Reservation", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("reservation_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationId"));

                    b.Property<int?>("ChambreId")
                        .HasColumnType("int")
                        .HasColumnName("chambre_id");

                    b.Property<DateTime?>("DateDebut")
                        .HasColumnType("datetime")
                        .HasColumnName("date_debut");

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("datetime")
                        .HasColumnName("date_fin");

                    b.Property<DateTime?>("DateReservation")
                        .HasColumnType("datetime")
                        .HasColumnName("date_reservation");

                    b.Property<int?>("SalleId")
                        .HasColumnType("int")
                        .HasColumnName("salle_id");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("int")
                        .HasColumnName("service_id");

                    b.Property<string>("StatutReservation")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("statut_reservation");

                    b.Property<string>("TypeReservation")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("type_reservation");

                    b.Property<int>("client_id")
                        .HasColumnType("int");

                    b.HasKey("ReservationId")
                        .HasName("PK__reservat__31384C29D704375C");

                    b.HasIndex("ChambreId");

                    b.HasIndex("SalleId");

                    b.HasIndex("client_id");

                    b.ToTable("reservation", (string)null);
                });

            modelBuilder.Entity("gestionhotel.Models.Salle", b =>
                {
                    b.Property<int>("SalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("salle_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SalleId"));

                    b.Property<int?>("CapaciteSalle")
                        .HasColumnType("int")
                        .HasColumnName("capacite_salle");

                    b.Property<string>("EquipementSalle")
                        .HasColumnType("text")
                        .HasColumnName("equipement_salle");

                    b.Property<string>("NomSalle")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nom_salle");

                    b.Property<string>("StatutSalle")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("statut_salle");

                    b.Property<double?>("TarifSalle")
                        .HasColumnType("float")
                        .HasColumnName("tarif_salle");

                    b.HasKey("SalleId")
                        .HasName("PK__salle__D882AF9BFF90B9B6");

                    b.ToTable("salle", (string)null);
                });

            modelBuilder.Entity("gestionhotel.Models.Service", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("service_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceId"));

                    b.Property<string>("DescriptionService")
                        .HasColumnType("text")
                        .HasColumnName("description_service");

                    b.Property<string>("NomService")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nom_service");

                    b.Property<int?>("ReservationId")
                        .HasColumnType("int")
                        .HasColumnName("reservation_id");

                    b.Property<string>("StatutService")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("statut_service");

                    b.HasKey("ServiceId")
                        .HasName("PK__service__3E0DB8AF71EF99C2");

                    b.HasIndex("ReservationId");

                    b.ToTable("service", (string)null);
                });

            modelBuilder.Entity("gestionhotel.Models.Client", b =>
                {
                    b.HasOne("gestionhotel.Models.Fidelite", "Fidelite")
                        .WithMany("Clients")
                        .HasForeignKey("FideliteId")
                        .HasConstraintName("FK__client__fidelite__571DF1D5");

                    b.Navigation("Fidelite");
                });

            modelBuilder.Entity("gestionhotel.Models.Reservation", b =>
                {
                    b.HasOne("gestionhotel.Models.Chambre", "Chambre")
                        .WithMany("Reservations")
                        .HasForeignKey("ChambreId")
                        .HasConstraintName("FK__reservati__chamb__5070F446");

                    b.HasOne("gestionhotel.Models.Salle", "Salle")
                        .WithMany("Reservations")
                        .HasForeignKey("SalleId")
                        .HasConstraintName("FK__reservati__salle__5165187F");

                    b.HasOne("gestionhotel.Models.Client", "client")
                        .WithMany("Reservations")
                        .HasForeignKey("client_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chambre");

                    b.Navigation("Salle");

                    b.Navigation("client");
                });

            modelBuilder.Entity("gestionhotel.Models.Service", b =>
                {
                    b.HasOne("gestionhotel.Models.Reservation", "Reservation")
                        .WithMany("Services")
                        .HasForeignKey("ReservationId")
                        .HasConstraintName("FK__service__reserva__5441852A");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("gestionhotel.Models.Chambre", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("gestionhotel.Models.Client", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("gestionhotel.Models.Fidelite", b =>
                {
                    b.Navigation("Clients");
                });

            modelBuilder.Entity("gestionhotel.Models.Reservation", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("gestionhotel.Models.Salle", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
